services:
  postgres:
    image: postgres:16
    container_name: taskflow-postgres
    environment:
      POSTGRES_DB: taskflow
      POSTGRES_USER: taskflow
      POSTGRES_PASSWORD: taskflow
    ports:
      - "5432:5432"
    volumes:
      - taskflow_db:/var/lib/postgresql/data
volumes:
  taskflow_db: